In [52]:
import torch as t 

a = t.randn(3*2*4)

In [53]:
a = a.reshape(3,2,4)
a

tensor([[[-1.3830e+00,  8.6476e-01, -3.1128e+00, -1.1088e+00],
         [ 1.6798e-01, -1.3277e+00, -1.8857e-01, -1.4046e+00]],

        [[-1.2726e+00,  1.8294e-01,  3.3442e+00,  8.1870e-01],
         [ 1.0582e+00,  9.0292e-01, -1.4321e-03,  1.0008e+00]],

        [[-8.8650e-01,  9.8501e-01,  1.8137e-01, -1.9648e-01],
         [-1.1715e-01,  1.4824e+00,  9.3089e-01,  4.9043e-01]]])

In [54]:
print(a.argmax(dim=0))
print(a.argmax(dim=0).shape)

tensor([[2, 2, 1, 1],
        [1, 2, 2, 1]])
torch.Size([2, 4])


In [55]:
print(a.argmax(dim=1))
print(a.argmax(dim=1).shape)

tensor([[1, 0, 1, 0],
        [1, 1, 0, 1],
        [1, 1, 1, 1]])
torch.Size([3, 4])


In [56]:
print(a.argmax(dim=-1))
print(a.argmax(dim=-1).shape)

tensor([[1, 0],
        [2, 0],
        [1, 1]])
torch.Size([3, 2])
