In [15]:
import torch as t

a = t.randint(12, size=(3,3,3,3))
print(a)
a = (a/255.0).mean(axis=(0,1,2))
b = (a/255.0).mean()

tensor([[[[ 3,  7,  4],
          [ 1,  9,  7],
          [ 7, 11, 10]],

         [[ 8,  8, 11],
          [ 2,  5,  1],
          [ 2,  8,  1]],

         [[ 5,  0,  0],
          [ 8,  7, 11],
          [ 2,  2,  0]]],


        [[[ 3,  9,  3],
          [ 6, 11,  6],
          [ 3,  8,  7]],

         [[ 8,  6,  8],
          [10,  4,  5],
          [ 4,  9,  0]],

         [[11,  2,  4],
          [ 4,  7,  8],
          [10,  7,  9]]],


        [[[ 1,  2,  5],
          [ 7,  7,  9],
          [10, 10, 10]],

         [[ 9,  8,  5],
          [ 8, 11,  4],
          [ 5,  4,  1]],

         [[ 3,  9,  5],
          [ 1,  4, 11],
          [ 8, 11,  0]]]])


In [16]:
print("a".center(50,"="))
print(a)
print("b".center(50,"="))
print(b)

========================a=========================
tensor([0.0216, 0.0270, 0.0211])
========================b=========================
tensor(9.1133e-05)


In [70]:
a = t.ones(size=(3,2,2,2))
a[0,0,0,0] += 3
a[0,0,0,0] += 2
a[0,0,0,0] += 1
a[0,1,0,0] -= 1
print(a)
a = (a).mean(axis=(0,1,2))
b = (a).mean()

print("a".center(50,"="))
print(a)
print("b".center(50,"="))
print(b)

tensor([[[[7., 1.],
          [1., 1.]],

         [[0., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
========================a=========================
tensor([1.4167, 1.0000])
========================b=========================
tensor(1.2083)


1.75