In [42]:
import torch as t
import torch.utils.data as data
import numpy as np

from torch.utils.data import TensorDataset

In [43]:
# randn(size)
data_ = t.arange(0,600).view(12,2,5,5)
data_

tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19],
          [ 20,  21,  22,  23,  24]],

         [[ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39],
          [ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49]]],


        [[[ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59],
          [ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74]],

         [[ 75,  76,  77,  78,  79],
          [ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]]],


        [[[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119],
          [120, 121, 122, 123, 124]],

         [[125, 126, 127, 128, 129],
          [130, 131, 132

In [44]:
# randint(시작,끝,(size))
labels = t.randint(1,100,(12,))
labels

tensor([39, 93, 32, 41, 59, 79, 28, 67,  3, 74, 63, 35])

In [45]:
# Must match the size[0] between data & labels
dataset = TensorDataset(data_, labels)
# next(iter(dataset))은 data set을 한개씩 보여주는 역할을 한다.
# 600개의 데이터에서 labels를 12개로 나눴기 때문에, 50개의 데이터가 총 12번씩 보이게 된다.
# 아래는 50, 50, 50 ... 개의 세트중 한개의 data set을 보여주는 것이고
# 맨 아래의 tensor는 label을 뜻한다.
# 최종적으로는 (50,1) = (data set, 레이블) x 12 개의 세트가 나온다.
next(iter(dataset))

(tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24]],
 
         [[25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39],
          [40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49]]]),
 tensor(39))

In [102]:
# Size = (12,2,5,5)
# Size[0]/batch_size 갯수만큼 data set가 나오게 된다.
dataloader = t.utils.data.DataLoader(dataset, batch_size=12, shuffle=True)

In [103]:
for i, (batch,labelss) in enumerate(dataloader):
    print(f"{i}".center(100,"="))
    print("Batch size : ", batch.size())
    print("Batch : ", batch)

    print("labels size : ", labelss.size())
    print("Labels : ", labelss)
    
print(f"Finish".center(100,"="))
print("Total Batch Sets : ", i + 1)

=================================================0==================================================
Batch size :  torch.Size([12, 2, 5, 5])
Batch :  tensor([[[[450, 451, 452, 453, 454],
          [455, 456, 457, 458, 459],
          [460, 461, 462, 463, 464],
          [465, 466, 467, 468, 469],
          [470, 471, 472, 473, 474]],

         [[475, 476, 477, 478, 479],
          [480, 481, 482, 483, 484],
          [485, 486, 487, 488, 489],
          [490, 491, 492, 493, 494],
          [495, 496, 497, 498, 499]]],


        [[[250, 251, 252, 253, 254],
          [255, 256, 257, 258, 259],
          [260, 261, 262, 263, 264],
          [265, 266, 267, 268, 269],
          [270, 271, 272, 273, 274]],

         [[275, 276, 277, 278, 279],
          [280, 281, 282, 283, 284],
          [285, 286, 287, 288, 289],
          [290, 291, 292, 293, 294],
          [295, 296, 297, 298, 299]]],


        [[[200, 201, 202, 203, 204],
          [205, 206, 207, 208, 209],
          [210, 211, 212